export const employees = [
    {
        name: 'Lisa Manoban',
        position: 'Junior Developer',
        email: 'lisa@bp.com',
        contact: '093048293',
        branch: 'New York, USA',
    },
    {
        name: 'Jennie Kim',
        position: 'Junior React Developer',
        email: 'jennie.k@bp.com',
        contact: '093048293',
        branch: 'New York, USA',
    },
    {
        name: 'Kim Woosik',
        position: 'Senior Node Developer',
        email: 'woosik@ps.com',
        contact: '093048293',
        branch: 'Seoul, South Korea',
    },
    {
        name: 'Rosie Park',
        position: 'Chief Technology Officer',
        email: 'lisa@bp.com',
        contact: '093048293',
        branch: 'New York, USA',
    },
    {
        name: 'Joen Jungkook',
        position: 'Senior tester',
        email: 'lisa@bp.com',
        contact: '093048293',
        branch: 'Bangkok, Thailand',
    },
    {
        name: 'RM Namjoon',
        position: 'Senior tester',
        email: 'lisa@bp.com',
        contact: '093048293',
        branch: 'New York, USA',
    },
    {
        name: 'Jennie Berg',
        position: 'Senior tester',
        email: 'lisa@bp.com',
        contact: '09304829213',
        branch: 'Bangkok, Thailand',
    },
    {
        name: 'Harry Potter',
        position: 'Senior tester',
        email: 'lisa@bp.com',
        contact: '093048234293',
        branch: 'Bangkok, Thailand',
    },
    {
        name: 'Maarten Styles',
        position: 'Senior tester',
        email: 'lisa@bp.com',
        contact: '093234048293',
        branch: 'Bangkok, Thailand',
    },
]